### ISSUE TITLE
Alternative of terminal link hinting

### ISSUE THREAD

**Issue by amosbird** [noctuid/link-hint.el#20]
Hi, I just came across this and skimmed through the last section of `README.md`. Have you tried 

https://bitbucket.org/sterlingcamden/urlpicker  ?

This is very snappy :)

**Comment by noctuid** [comment]
I may have tried it at one point when I was using urxvt. I don't use urxvt currently, so the downsides are that it is urxvt only (unlike the generic tmux plugins), and it looks like it doesn't have customizable hint keys (same problem as tmux-fingers, but at least tmux-fingers uses letters instead of numbers).
